version: '3.8'

services:
  top-process-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    image: top-process-exporter:latest
    container_name: top-process-exporter
    restart: unless-stopped
    ports:
      - "9258:8000"
    environment:
      - TOP_N=30
      - CACHE_SECONDS=20
    # Host process access
    pid: host
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 